# .github/workflows/publish.yml
name: Generate a build and push to another branch

on:
  push:
    branches:
      - '*' # Trigger on any branch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8.15.5

      - name: Install all dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build:node:cjs # The build command of your project

      - name: Commit and Push All Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated build: $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
